# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0-alpha.22
maven_group=net.azureaaron.dandelion
archives_base_name=dandelion

# Dependencies
fabric_version=0.152.1+26.2
yacl_version=3.9.4+26.2
moulconfig_flavour=modern-26.2
moulconfig_version=4.7.2
#moulconfig_version=9999.9999.9999
flk_version=1.13.12+kotlin.2.4.0

# Miscellaneous
shadow_version=9.4.2
spotless_version=8.7.0
checkstyle_version=13.6.0
